# Generated by Django 2.1.1 on 2019-01-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='freeDay',
            new_name='freeTime',
        ),
    ]
