# Generated by Django 2.1.4 on 2019-01-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190101_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dayChosen',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='response',
            name='freeTime',
            field=models.CharField(max_length=2048),
        ),
    ]
